In [13]:
from scipy.stats import norm
import pandas as pd
from numpy import dot
from numpy.linalg import norm
import datetime
import random

In [14]:
df = pd.read_csv("test.csv")
df3 = pd.read_csv("test3.csv")
df
df3

,Unnamed: 0,Unnamed: 0.1,일련번호,회원번호,이름,성별,나이,주소,생일,핸드폰번호,...,최종 주문시간,최종 주문 요일,주말여부,제품코드,대분류,중분류,세분류,제품이름,구매액,수량
0,7,10,11,100000011,염기준,M,41,서울 강서구 가양3동,5월 12일,990-2447-6185,...,11:55,일,T,20338,1,17,3,절전형 전기매트 싱글 3개,92500,1.0
1,10,13,14,100000014,이세연,F,24,서울 강서구 가양3동,5월 12일,990-1349-4434,...,1:14,금,F,20230,2,5,5,시즌6,102500,1.0
2,14,18,19,100000019,전기복,M,50,경기 고양시 고양동,7월 28일,990-6416-6162,...,15:55,일,T,20183,2,16,2,스마트 2015,65500,1.0
3,19,28,29,100000029,곽용선,F,63,서울 은평구 증산동,4월 11일,990-9456-4523,...,14:38,일,T,20873,2,12,1,무료체험() 버블샴푸2.8L,70300,1.0
4,21,31,32,100000032,김하빈,F,59,경기 고양시 성사동,7월 25일,990-2929-4567,...,22:53,금,F,20542,2,5,3,대용량 레드 믹서기,113300,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
206710,332873,499991,499992,100499992,이혜빈,F,45,경기 고양시 삼송동,9월 6일,990-3921-2738,...,9:15,목,F,20579,14,11,3,일레스틱 골프바지 3종,63300,1.0
206711,332874,499993,499994,100499994,강경희,F,44,서울 성북구 길음동,7월 30일,990-7058-0197,...,17:42,일,T,20190,2,25,14,LA갈비 10팩_총 5kg,73400,1.0
206712,332876,499995,499996,100499996,김미녀,F,24,경기 고양시 가좌동,11월 5일,990-7792-9213,...,6:48,금,F,20427,3,2,2,사은품_라면:,0,1.0
206713,332878,499998,499999,100499999,이재순,F,60,서울 마포구 망원동,1월 1일,990-4403-4596,...,20:40,일,T,20792,2,12,1,무료체험 탈모샴푸,83300,1.0
206714,332879,499999,500000,100500000,박하랑,M,66,경기 고양시 일산3동,7월 8일,990-1312-9533,...,13:40,수,F,20435,2,6,2,유기농 엑스트라버진 넛오일,71400,1.0

In [15]:
def mean_attr(X,Y,Z): # U1 : Mean Attribute (10%)
    a = X[Z][0]
    try:
            a == int(a) ## 만약 숫자를 입력하지 않는  다면 예외처리!
    except ValueError:
            print("Input number value!")
            pass
            return
    meanDiff=X[Z].mean()-Y[Z].mean()
    return abs(meanDiff)

In [16]:
print(mean_attr(df,df3,'나이'))

1.26846561420313

In [17]:
print(df['전년도 누적금액'][0])
df['구매액'][0]

381700

63400

In [18]:
def mean_corr(X,Y,Z): # U2 : Mean Correlation (10%)
    mean_sum = 0
    for i in Z:
        a = X[i][0] ## 데이터 하나를 추출하여 int형으로 강제 형변환 한것과 비교,,, 같은 경우 정수형으로 보고 인식
        try:
                a == int(a) ## 만약 숫자를 입력하지 않는  다면 예외처리!
        except ValueError: ## 값이 일치하지 않을 경우
                print("Input number value!") ## 에러메세지 출력
                pass
                return ## NULL 값 반환(아무것도 반환 안함)
        df_corr = pd.DataFrame({'x': X[i], 'y': Y[i]}) ## KL과정을 거치기 전 df X와 거친 후 Y의 Z열(KL처리를 한 항목) 값을 받아서 데이터프레임 생성
        meanCorr=df_corr.corr(method='pearson') ## 피어슨 상관계수 계산 (df 자체적으로 돌아감)
        print(df_corr.corr(method='pearson'))
        print(meanCorr.iloc[0,1])
        mean_sum += meanCorr.iloc[0,1]
    return abs(mean_sum) ## 피어슨 상관계수 값 추출 0,1 즉 서로 다른 열을 계산한 값을 출력함,,,, 아래의 출력창 참고

In [ ]:
k = {'구매액','수량','전년도 누적금액'}
print(mean_corr(df,df3,k))

In [19]:
def cos_sim(X, Y, Z): # U3 : Cosine Similarity (10%)
    a = X[Z][0]
    try:
            a == int(a) ## 만약 숫자를 입력하지 않는  다면 예외처리!
    except ValueError:
            print("Input number value!")
            pass
            return
    meanSim = dot(X[Z],Y[Z])/(norm(X[Z])*norm(Y[Z]))    
    return meanSim

In [20]:
print(cos_sim(df,df3,'전년도 누적금액'))

ValueError: shapes (500000,) and (206715,) not aligned: 500000 (dim 0) != 206715 (dim 0)

In [13]:
def info_loss(X, Y, Z): # U4 : Information Loss (15%), 지정된 특정 컬럼들에 대한 정형화된 차이값들의 평균
    # X.shape = Y.shape
    a = X[Z][0]
    try:
            a == int(a) ## 만약 숫자를 입력하지 않는  다면 예외처리!
    except ValueError:
            print("Input number value!")
            pass
            return    
    value = 0
    value=abs(X[Z]]-Y[]])/abs(X.iloc[i,j])
    return total/len(Y.columns)*len(Y.index)

In [14]:
print(mean_attr(df,df3,'나이'))

1.26846561420313

In [15]:
print(df['전년도 누적금액'][0])
df['구매액'][0]

381700

63400