In [1]:
from scipy.stats import norm
from faker import Faker
import pandas as pd
import numpy as np
import datetime
import random

In [2]:
# 핸드폰 번호 생성
def randPhoneNumber() :
    phone_number = fake.phone_number().split('-')
    phone_number[0] = '010'        # 핸드폰 첫자리가 02, 016 등을 모두 010으로 강제 고정
    if len(phone_number[1]) == 3 : # 016-123-4567과 같이 가운데가 3자리일경우 랜덤 숫자 1개 추가
        phone_number[1] = phone_number[1] + str(random.randrange(10))
    phone_number = '-'.join(phone_number)
    return phone_number

In [3]:
# 주소 생성. 랜덤 추출
def randAddress():
    listing = ['서울특별시 중구', '서울특별시 용산구', '서울특별시 마포구', '서울특별시 강서구', '서울특별시 영등포구', '서울특별시 동작구', '서울특별시 강남구', '서울특별시 송파구', '서울특별시 강동구', '서울특별시 서초구', '서울특별시 중랑구', '서울특별시 성북구', '서울특별시 노원구', '서울특별시 은평구', '서울특별시 양천구', '서울특별시 구로구', '서울특별시 금천구', '서울특별시 종로구', '서울특별시 성동구', '서울특별시 광진구', '서울특별시 동대문구', '서울특별시 강북구', '서울특별시 도봉구', '서울특별시 서대문구', '서울특별시 관악구', '충청북도 청원군', '충청북도 청주시 흥덕구', '충청북도 충주시', '충청북도 진천군', '충청북도 청주시 상당구', '충청북도 음성군', '충청북도 영동군', '충청북도 단양군', '충청북도 청주시 청원구', '충청북도 청주시 서원구', '충청북도 보은군', '충청북도 제천시', '충청북도 옥천군', '충청북도 증평군', '충청북도 괴산군', '충청남도 아산시', '충청남도 당진군', '충청남도 논산시', '충청남도 계룡시', '충청남도 공주시', '충청남도 연기군', '충청남도 홍성군', '충청남도 천안시 동남구', '충청남도 천안시 서북구', '충청남도 천안시', '충청남도 청양군', '충청남도 보령시', '충청남도 서산시', '충청남도 금산군', '충청남도 부여군', '충청남도 예산군', '충청남도 당진시', '충청남도 서천군', '충청남도 태안군', '제주특별자치도 제주시', '제주특별자치도 서귀포시', '전라북도 남원시', '전라북도 장수군', '전라북도 순창군', '전라북도 완주군', '전라북도 전주시 덕진구', '전라북도 전주시 완산구', '전라북도 진안군', '전라북도 임실군', '전라북도 전주시', '전라북도 익산시', '전라북도 김제시', '전라북도 무주군', '전라북도 고창군', '전라북도 부안군', '전라북도 정읍시', '전라북도 군산시', '전라남도 담양군', '전라남도 순천시', '전라남도 영광군', '전라남도 장성군', '전라남도 나주시', '전라남도 강진군', '전라남도 해남군', '전라남도 목포시', '전라남도 여수시', '전라남도 광양시', '전라남도 화순군', '전라남도 구례군', '전라남도 보성군', '전라남도 장흥군', '전라남도 영암군', '전라남도 무안군', '전라남도 함평군', '전라남도 신안군', '전라남도 진도군', '전라남도 곡성군', '전라남도 고흥군', '전라남도 완도군', '인천광역시 남구', '인천광역시 미추홀구', '인천광역시 연수구', '인천광역시 남동구', '인천광역시 중구', '인천광역시 동구', '인천광역시 부평구', '인천광역시 계양구', '인천광역시 서구', '인천광역시 강화군', '울산광역시 울주군', '울산광역시 북구', '울산광역시 중구', '울산광역시 남구', '부산광역시 기장군', '부산광역시 부산진구', '부산광역시 연제구', '부산광역시 동래구', '부산광역시 남구', '부산광역시 북구', '부산광역시 금정구', '부산광역시 강서구', '부산광역시 서구', '부산광역시 동구', '부산광역시 사상구', '부산광역시 해운대구', '부산광역시 수영구', '부산광역시 영도구', '부산광역시 사하구', '대전광역시 유성구', '대전광역시 동구', '대전광역시 대덕구', '대전광역시 서구', '대전광역시 중구', '대구광역시 달성군', '대구광역시 서구', '대구광역시 중구', '대구광역시 남구', '대구광역시 달서구', '대구광역시 동구', '대구광역시 북구', '대구광역시 수성구', '광주광역시 동구', '광주광역시 서구', '광주광역시 북구', '광주광역시 남구', '광주광역시 광산구', '경상북도 고령군', '경상북도 상주시', '경상북도 울진군', '경상북도 포항시 남구', '경상북도 포항시 북구', '경상북도 김천시', '경상북도 포항시', '경상북도 경산시', '경상북도 청도군', '경상북도 청송군', '경상북도 경주시', '경상북도 안동시', '경상북도 구미시', '경상북도 영주시', '경상북도 영천시', '경상북도 성주군', '경상북도 예천군', '경상북도 문경시', '경상북도 영양군', '경상북도 의성군', '경상북도 영덕군', '경상북도 칠곡군', '경상북도 군위군', '경상북도 봉화군', '경상남도 함양군', '경상남도 거창군', '경상남도 합천군', '경상남도 산청군', '경상남도 양산시', '경상남도 함안군', '경상남도 김해시', '경상남도 창원시 진해구', '경상남도 의령군', '경상남도 창녕군', '경상남도 밀양시', '경상남도 창원시 의창구', '경상남도 창원시 성산구', '경상남도 창원시 마산합포구', '경상남도 창원시 마산회원구', '경상남도 창원시', '경상남도 진주시', '경상남도 사천시', '경상남도 거제시', '경상남도 고성군', '경상남도 하동군', '경상남도 통영시', '경상남도 남해군', '경기도 여주군', '경기도 부천시 원미구', '경기도 부천시 소사구', '경기도 부천시 오정구', '경기도 평택시', '경기도 시흥시', '경기도 오산시', '경기도 김포시', '경기도 이천시', '경기도 안산시 단원구', '경기도 수원시 팔달구', '경기도 용인시 처인구', '경기도 화성시', '경기도 안성시', '경기도 수원시 권선구', '경기도 광주시', '경기도 성남시', '경기도 성남시 중원구', '경기도 안양시 동안구', '경기도 부천시', '경기도 고양시 일산서구', '경기도 과천시', '경기도 남양주시', '경기도 고양시 덕양구', '경기도 가평군', '경기도 수원시 장안구', '경기도 수원시 영통구', '경기도 용인시 기흥구', '경기도 수원시', '경기도 성남시 수정구', '경기도 성남시 분당구', '경기도 의정부시', '경기도 안양시', '경기도 안양시 만안구', '경기도 파주시', '경기도 광명시', '경기도 동두천시', '경기도 안산시 상록구', '경기도 고양시 일산동구', '경기도 의왕시', '경기도 하남시', '경기도 용인시 수지구', '경기도 용인시', '경기도 여주시', '경기도 양주시', '경기도 포천시', '경기도 연천군', '경기도 양평군', '경기도 안산시', '경기도 구리시', '경기도 군포시', '강원도 원주시', '강원도 삼척시', '강원도 영월군', '강원도 강릉시', '강원도 동해시', '강원도 태백시', '강원도 속초시', '강원도 홍천군', '강원도 횡성군', '강원도 평창군', '강원도 정선군', '강원도 철원군', '강원도 화천군', '강원도 양구군', '강원도 인제군', '강원도 고성군', '강원도 양양군', '강원도 춘천시']
    return listing[random.randint(0,len(listing)-1)]

In [4]:
# 나이 생성. 나이대별 퍼센트별로 랜덤 생성인듯?
def randOld():
  rv = norm(loc = 44 , scale = 10)
  y = rv.rvs(size=1)
  return int(y) ## 65세 이상 13.8 퍼센트 /14세 이상 65세 미만 73.2퍼센트 / 14세 미만 13.1퍼센트

In [5]:
# 가족관계 생성. 랜덤 추출
def randfamily(input):
    family = ['외동딸', '외동아들', '1남1녀', '1남2녀', '2남1녀', '다자녀', '실부실모', '편부', '편모']
    if input["sex"] == "F" :     # 여자면 외동아들 제외
        family.remove("외동아들")
    else :                       # 남자면 외동딸 제외
        family.remove("외동딸")
    return random.choice(family)

In [6]:
# 예시 데이터 생성

data_count = 100      # 생성할 데이터 개수

fake = Faker("ko_KR")

df = pd.DataFrame(columns=('name',
                           'email',
                           'phone',
                           'age',
                           'sex',
                           'address',
                           # 'weight' 아래에서 추가
                           # 'Port' 아래에서 추가
                           # 'Credit' 아래에서 추가
                           'family'
                           # 'Operation' 아래에서 추가
                          )
                 )

for i in range(data_count):
    buffer = fake.profile()
    stuff = [buffer["name"],
             buffer["mail"],
             randPhoneNumber(),
             randOld(),
             buffer["sex"],
             randAddress(),
             # weight 아래에서 추가
             # port 아래에서 추가
             # credit 아래에서 추가
             randfamily(buffer)
             # operation 아래에서 추가
            ]
    df.loc[i] = [item for item in stuff]

df = df.astype({'age':'int'})

In [7]:
# 몸무게 추가
def randWeight(df):
    weightList=[] # df 항목들의 weight가 쌓일 list
    
    for i in df.index:
        val = df.loc[i] # for문이 실행되는 row 
        weight = 0 # weight 변수 초기화

        if val.sex == "M": # 남성일 때
            if val.age < 30: # sizeofkorea를 기반으로 나이에 따라 대략적인 평균몸무게 산출
                weight = 13/14*val.age+47.8
            else: # val.age >= 30:
                weight = -3/25*(val.age-30)+76.3

        else: # val.sex == "F" 여성일 때
            if val.age < 20:
                weight = 7/4*val.age+91/4
            elif val.age < 40:
                weight = 4/15*val.age+(149/3)
            else: # val.age >= 40:
                weight = 0.1*val.age+54

        weightList.append(format(weight,".2f")) # 산출된 몸무게를 list에 append

    df.loc[:,'weight'] = weightList # for문을 통해 산출된 몸무게 리스트를 사용해 "weight" column에 추가
    
    return df
randWeight(df)

,name,email,phone,age,sex,address,family,weight
0,최현주,seoyungo@gmail.com,010-7715-0703,47,F,경기도 과천시,1남2녀,58.70
1,권민수,ohwang@naver.com,010-7779-5912,47,M,경상남도 창원시 마산회원구,편부,74.26
2,이지영,yeongceol01@hanmail.net,010-1729-2441,38,F,경기도 광명시,편부,59.80
3,김현정,misug11@hotmail.com,010-3712-2711,65,F,경기도 김포시,실부실모,60.50
4,이동현,isanghun@dreamwiz.com,010-0248-6908,32,M,울산광역시 중구,1남2녀,76.06
...,...,...,...,...,...,...,...,...
95,이상훈,cgim@naver.com,010-7322-5225,48,M,서울특별시 성북구,1남1녀,74.14
96,김중수,jeongsugbag@hanmail.net,010-2742-5064,41,M,인천광역시 부평구,편부,74.98
97,이예지,minjaejeon@naver.com,010-0137-5740,54,F,충청남도 청양군,편부,59.40
98,이재현,dbag@gmail.com,010-2933-1072,21,M,경기도 수원시,외동아들,67.30
99,최경수,caeweonbag@nate.com,010-3911-2376,16,M,서울특별시 중랑구,외동아들,62.66

In [8]:
# 주민번호 추가
def randPort(DataFrame):
    df_Port = DataFrame.loc[:,('age','sex')]   #나이와 성별을 가져옴
    now = datetime.datetime.now()
    nowyear=int(str(now).split('-')[0])         #현재년도를 가져옴
    dataPort = {}
    resultlist = []
    for i in range(len(df_Port.index)):          #데이터프레임 인덱스 수만큼 반복
        year = df_Port.iloc[:,0][i]
        sex = df_Port.iloc[:,1][i]
        two = nowyear-int(year)-1                #현재년도에서 나이를 빼고 1을 더하여 태어난 년도 구함
        x = random.randint(1,12)                 #태어난 달
        x1 = lambda x : str(x) if x>= 10 else '0'+str(x)      #태어난 달이 10보다 크면 문자화, 10보다 작으면 앞에 0을 붙여서 문자화
        birthday = x1(x)+ x1(random.randint(1,31))            #태어난 달과 날을 합침
        flag =0
        last = ""
        while len(last) != 6:                   #뒷번호 성별구별을 제외한 6자리를 구할만큼 반복
            temp = str(random.randint(10**(5-len(last)),10**(6-len(last))))
            if len(temp) == 6-len(last) :
                last += temp
                break
            else :
                continue
        if sex == 'M':                #성별구별 남자=1, 여자=2
            flag = 1
        else :
            flag = 2
        resultlist.append(str(two)[-2:]+birthday+'-'+str(flag)+last)        #리스트에 생년월일-뒷번호 추가
        pd.unique(resultlist).tolist()         #중복값이 있을경우 마지막 중복값을 삭제 후 순서유지
        i-=1                        #중복값이 삭제되었을 때 다시 값생성을 위한 i 감소
    dataPort['주민등록번호'] = resultlist
    #Port = pd.DataFrame(dataPort)
    df.loc[:,'port'] = resultlist
    #return Port
    return df
randPort(df)

,name,email,phone,age,sex,address,family,weight,port
0,최현주,seoyungo@gmail.com,010-7715-0703,47,F,경기도 과천시,1남2녀,58.70,720502-2388424
1,권민수,ohwang@naver.com,010-7779-5912,47,M,경상남도 창원시 마산회원구,편부,74.26,720229-1567942
2,이지영,yeongceol01@hanmail.net,010-1729-2441,38,F,경기도 광명시,편부,59.80,810612-2154948
3,김현정,misug11@hotmail.com,010-3712-2711,65,F,경기도 김포시,실부실모,60.50,540808-2385995
4,이동현,isanghun@dreamwiz.com,010-0248-6908,32,M,울산광역시 중구,1남2녀,76.06,870821-1581949
...,...,...,...,...,...,...,...,...,...
95,이상훈,cgim@naver.com,010-7322-5225,48,M,서울특별시 성북구,1남1녀,74.14,710830-1833162
96,김중수,jeongsugbag@hanmail.net,010-2742-5064,41,M,인천광역시 부평구,편부,74.98,781207-1254000
97,이예지,minjaejeon@naver.com,010-0137-5740,54,F,충청남도 청양군,편부,59.40,650111-2886100
98,이재현,dbag@gmail.com,010-2933-1072,21,M,경기도 수원시,외동아들,67.30,981022-1393985
99,최경수,caeweonbag@nate.com,010-3911-2376,16,M,서울특별시 중랑구,외동아들,62.66,030617-1486664

In [9]:
# 질병 기록 추가
def randOperation(DataFrame):     
    dataOP={}
    OP_result=[]
    OP_list=['폐암', '간암', '대장암', '위암', '췌장암', '패혈증', '당뇨병', '폐렴', '백혈병', '뇌암', '혈관성 치매', '결핵', '우울증', '틱증', '신경증', '정신분열증', '조증','급성위염', '담석증', '위궤양', '충수염', '크론병', '알츠하이머', '수두', '노카르디아증', '홍역', '장티푸스', '콜레라', '야콥병', '무좀', '모닐리아증', '갑상선기증저하증', '고지혈증', '저혈당증', '쿠싱증후군', '간질', '뇌염', '말초신경염', '불면증', '척수염', '파킨슨병', '안면신경마비', '빈혈', '자반', '혈우병', '결장암', '골수종', '뇌종양', '백혈병', '악성후두종양', '호치킨병', '각막염', '결막염', '고막염', '녹내장', '맥립종', '메니에르병', '백내장', '안검염', '헤르페스성각막염', '요도염', '신우신염', '네프로제', '방광염', '신결석', '신부전', '골다공증', '골수염', '골절', '관절염', '디스크', '통풍', '다운증후군', '척추관협착증','요로결석', '뇌출혈', '뇌경색', '심근경색', '유방암']
    
    W_OP_list=OP_list+['자궁암', '난소종양', '자궁근종', '질염', '내궁내막증', '자궁경부암', '융모상피암', '바톨린염']      #OP_list에 여성질환 추가한 리스트
    
    M_OP_list=OP_list+['전립선염', '전립선비대증', '전립선암', '부고환 낭종', '고환암', '귀두염', '음낭수종', '페로니병']    #OP_list에 남성질환 추가한 리스트
    
    df_OP = DataFrame.loc[:,('sex')]        #성별을 가져옴
    for i in range(len(df_OP.index)):         #데이터프레임 인덱스 수만큼 반복
        sex = df_OP.iloc[i]    
        if sex=='F':
             OP_result.append(W_OP_list[random.randint(0,len(W_OP_list)-1)])       #성별이 여자일 경우 W_OP_list에서 랜덤선별하여 OP_result리스트에 추가
        else :
             OP_result.append(M_OP_list[random.randint(0,len(M_OP_list)-1)])       #성별이 남자일 경우 M_OP_list에서 랜덤선별하여 OP_result리스트에 추가
    #dataOP['질병기록'] = OP_result
    #Operation = pd.DataFrame(dataOP)
    df.loc[:,'operation'] = OP_result
    return df
randOperation(df)

,name,email,phone,age,sex,address,family,weight,port,operation
0,최현주,seoyungo@gmail.com,010-7715-0703,47,F,경기도 과천시,1남2녀,58.70,720502-2388424,뇌염
1,권민수,ohwang@naver.com,010-7779-5912,47,M,경상남도 창원시 마산회원구,편부,74.26,720229-1567942,백혈병
2,이지영,yeongceol01@hanmail.net,010-1729-2441,38,F,경기도 광명시,편부,59.80,810612-2154948,골수염
3,김현정,misug11@hotmail.com,010-3712-2711,65,F,경기도 김포시,실부실모,60.50,540808-2385995,골다공증
4,이동현,isanghun@dreamwiz.com,010-0248-6908,32,M,울산광역시 중구,1남2녀,76.06,870821-1581949,녹내장
...,...,...,...,...,...,...,...,...,...,...
95,이상훈,cgim@naver.com,010-7322-5225,48,M,서울특별시 성북구,1남1녀,74.14,710830-1833162,대장암
96,김중수,jeongsugbag@hanmail.net,010-2742-5064,41,M,인천광역시 부평구,편부,74.98,781207-1254000,디스크
97,이예지,minjaejeon@naver.com,010-0137-5740,54,F,충청남도 청양군,편부,59.40,650111-2886100,뇌염
98,이재현,dbag@gmail.com,010-2933-1072,21,M,경기도 수원시,외동아들,67.30,981022-1393985,호치킨병
99,최경수,caeweonbag@nate.com,010-3911-2376,16,M,서울특별시 중랑구,외동아들,62.66,030617-1486664,심근경색

In [10]:
# 카드 번호 추가
def randCredit():
    credit_chk_list = [] # 생성된 신용카드 번호 저장 리스트
    while True:
        credit_num = "" #신용카드 번호 
        for i in range(4):
            for j in range(4):  
                credit_num = credit_num + str(random.randint(0, 9))#랜덤으로 0~9 까지 1자리씩 번호 생성 
            credit_num = credit_num + '-' # 4자리마다 - 추가
        credit_chk_list.append(credit_num[:-1])  #credit_chk_list에 추가하기전 [:-1]로 마지막 '-'를 제외 후 추가
        set(credit_chk_list) #신용카드번호 중복 제거 
        if(len(credit_chk_list)==10000): #중복 제거 후 100000개가 되면 while문 종료
            break
        else:
            continue
    return credit_chk_list # 100000개 저장된 리스트 반환

credit_list = randCredit()
creditlist = [credit_list[i] for i in range(data_count)]
df.loc[:,'credit'] = creditlist
df.head()

,name,email,phone,age,sex,address,family,weight,port,operation,credit
0,최현주,seoyungo@gmail.com,010-7715-0703,47,F,경기도 과천시,1남2녀,58.70,720502-2388424,뇌염,3869-0755-8054-7604
1,권민수,ohwang@naver.com,010-7779-5912,47,M,경상남도 창원시 마산회원구,편부,74.26,720229-1567942,백혈병,8311-7452-2592-2087
2,이지영,yeongceol01@hanmail.net,010-1729-2441,38,F,경기도 광명시,편부,59.80,810612-2154948,골수염,3678-5717-2984-0969
3,김현정,misug11@hotmail.com,010-3712-2711,65,F,경기도 김포시,실부실모,60.50,540808-2385995,골다공증,2914-8509-8947-5417
4,이동현,isanghun@dreamwiz.com,010-0248-6908,32,M,울산광역시 중구,1남2녀,76.06,870821-1581949,녹내장,4582-4363-1171-5092

In [11]:
import nltk
nltk.download('wordnet')
from nltk.corpus import wordnet ## 상위어를 뽑아내기 위한 사전파일 다운

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\dlals\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

In [12]:
pip install googletrans

Requirement already satisfied: googletrans in c:\users\dlals\anaconda3\lib\site-packages (3.0.0)
Requirement already satisfied: httpx==0.13.3 in c:\users\dlals\anaconda3\lib\site-packages (from googletrans) (0.13.3)
Requirement already satisfied: hstspreload in c:\users\dlals\anaconda3\lib\site-packages (from httpx==0.13.3->googletrans) (2020.10.6)
Requirement already satisfied: idna==2.* in c:\users\dlals\anaconda3\lib\site-packages (from httpx==0.13.3->googletrans) (2.10)
Requirement already satisfied: chardet==3.* in c:\users\dlals\anaconda3\lib\site-packages (from httpx==0.13.3->googletrans) (3.0.4)
Requirement already satisfied: httpcore==0.9.* in c:\users\dlals\anaconda3\lib\site-packages (from httpx==0.13.3->googletrans) (0.9.1)
Requirement already satisfied: certifi in c:\users\dlals\anaconda3\lib\site-packages (from httpx==0.13.3->googletrans) (2020.6.20)
Requirement already satisfied: rfc3986<2,>=1.3 in c:\users\dlals\anaconda3\lib\site-packages (from httpx==0.13.3->googletrans) (1.4.0)
Requirement already satisfied: sniffio in c:\users\dlals\anaconda3\lib\site-packages (from httpx==0.13.3->googletrans) (1.1.0)
Requirement already satisfied: h11<0.10,>=0.8 in c:\users\dlals\anaconda3\lib\site-packages (from httpcore==0.9.*->httpx==0.13.3->googletrans) (0.9.0)
Requirement already satisfied: h2==3.* in c:\users\dlals\anaconda3\lib\site-packages (from httpcore==0.9.*->httpx==0.13.3->googletrans) (3.2.0)
Requirement already satisfied: hpack<4,>=3.0 in c:\users\dlals\anaconda3\lib\site-packages (from h2==3.*->httpcore==0.9.*->httpx==0.13.3->googletrans) (3.0.0)
Requirement already satisfied: hyperframe<6,>=5.2.0 in c:\users\dlals\anaconda3\lib\site-packages (from h2==3.*->httpcore==0.9.*->httpx==0.13.3->googletrans) (5.2.0)
Note: you may need to restart the kernel to use updated packages.

In [13]:
from googletrans import Translator
translator = Translator()
list_trans = []
for i in df['operation'].unique():
    list_trans.append(translator.translate(i).text)

In [14]:
## 오퍼레이션에 있는 값들이 영어로 번역된것.
list_trans

['encephalitis',
 'leukemia',
 'Osteomyelitis',
 'osteoporosis',
 'glaucoma',
 'Cerebral hemorrhage',
 "Athlete's foot",
 'Myocardial infarction',
 'Breast cancer',
 'Liver cancer',
 'Cerebral infarction',
 'Keratitis',
 'Brain cancer',
 'blood poisoning',
 'cholera',
 'Nephroze',
 'neurosis',
 'Pyelonephritis',
 'Lung cancer',
 'Ovarian tumor',
 'Hypoglycemia',
 'Fracture',
 "Meniere's disease",
 'Hypothyroidism',
 'Stomach cancer',
 'Peripheral neuritis',
 'Hochkin disease',
 'Hyperlipidemia',
 'Pneumonia',
 'Choriocarcinoma',
 'Scrotal edema',
 'Fibroids',
 "Jacob's disease",
 'Schizophrenia',
 'Cushing syndrome',
 'Endometriosis',
 'Manic',
 'Colon cancer',
 'Nocardia',
 'Facial nerve palsy',
 'ventilation',
 'Enlarged prostate',
 "Alzheimer's",
 'appendicitis',
 'Urethritis',
 'Balanitis',
 'Stomach ulcer',
 'Allele',
 'anemia',
 'New absence',
 'Acute gastritis',
 'myelitis',
 'Bartholinitis',
 'varicella',
 'Tuberculosis',
 'Herpetic keratitis',
 'depression',
 'disk']

In [15]:
## pyelonephritis 는 신우신염이라는 증상, 영어로 해석
for synset in wordnet.synsets('pyelonephritis'):
    print("{}: {}".format(synset.name(), synset.definition()))
    synonyms = ", ".join([lem.name() for lem in synset.lemmas()])
    print("synonyms: {}".format(synonyms)) ## 동의어 뽑아내기
    
    hypernyms = ", ".join([hypernym.name() for hypernym in synset.hypernyms()])
    print("hypernyms: {}".format(hypernyms.split('.')[0])) ## 상위어 뽑아내기
    print()
## http://blog.naver.com/PostView.nhn?blogId=sara4938_&logNo=221063546103

pyelonephritis.n.01: inflammation of the kidney and its pelvis caused by bacterial infection
synonyms: pyelonephritis
hypernyms: urinary_tract_infection

In [ ]:
import hashlib
class anonymous() :
    def __init__(self,df):
        self.df = df
        self.backup = backup
    def sha256withSalt(self,columns,salt):
        ## listing = df.columns 선택할 칼럼 GUI 구성
        ## 선택한 프레임 고르기
        ## 다시 되돌리기 위한 백업 파일 구상
        ## sha256 + salt 를 하는 함수
        self.backup = self.df[columns]
        b = hashlib.sha256()
        c = []
        for i in range(len(df.index)):
            b.update((str(df.loc[i][columns])+str(salt)).encode('euc-kr'))
            c.append(b.hexdigest())
        new_c = np.array(c)
        return new_c
    def suppression_columns(self,columns):
        self.df.drop(columns,axis=1,inplace=True)
        self.backup = self.df[columns]
        ## 다시 되돌리기 위한 백업 구상
        ## 칼럼 전체를 삭제하는 함수
    def suppression_index(self,index):
        self.df.drop(index,axis=0,inplace=True)
        self.backup = df[index]
        ## 다시 되돌리기 위한 백업구상
        ## 특정 인덱스 삭제
    def fix(self,index,columns,value):
        self.df.at[index,columns] = value
        ## 특정 인덱스와 컬럼에 값 변경
    def partial_suppression_columns(self,columns,right,left):
        self.backup = self.df[columns]
        listing = self.df[columns].unique()
        least_len = listing[0] ## 데이터중 가장 짧은 길이의 문자열 생각
        for i in listing :
            if least_len >= len(i) :
                least_len = len(i) ## 최소 범위 제시
        for i in range(len(self.df.index)):
            string = self.df.loc[i,columns] ## 행 하나마다 문자열 추출
            if right < len(string) and left > 0 :
                self.df.at[i,columns] = "".join(string.split(string[left-1,right]))
        ## 칼럼의 데이터의 일부를 삭제하는 함수
        ## 구분자를 통한 자르는 것도 생각.
    def masking(self,columns,direction,number,mask):
        self.backup = self.df[columns]
        for i in range(len(df.index)):
            string = self.df.loc[i,columns]
            if direction == 'right' :
                string = string.replace(string[-number:],mask*number) 
                ## number 의 범위 설정 조심 (index)
                ## try catch로 잡을수도 있음.
            elif direction == "left" :
                string = string.replace(string[0:number+1],mask*number)
                ## number 의 범위 설정 조심 (index)
            self.df.at[i,columns] = string
    def aggregation(self,columns):
        col_mean = 0 ## 평균
        col_min = 0 ## 최소값
        col_max = 0 ## 최대값
        col_middle = 0 ## 중앙값
        col_often = 0 ## 최빈값
        if self.df[columns].dtypes != "object" : ## 숫자로 표현할수있는값
            col_mean = df[columns].mean()
            col_min = df[columns].min()
            col_max = df[columns].max()
            col_middle = df[columns].median()
            col_often = df[columns].mode()
            for i in range(len(df.index)):
               # self.df.at[i,columns] = col_, , , 
               # 전체 수치값에다가 적용시킨다. 
        else :
            return
    def number_interval(self,columns,number):
        ## number 로 구분해서 나눈다 파티션이 아니라 숫자형 데이터에 해당
        self.backup = self.df[columns]
        listing = self.df[columns].unique()
        list_min= listing.min()
        list_max= listing.max()
        ## min 과 max를 기준으로 구간을 나눈다.10 -> [10,20) 이런식
        ## 추가적인 내용 필요함